#!/bin/bash

# Log output:
#
# * 51c333e    (12 days)    <Gary Bernhardt>   add vim-eunuch
#
# The time massaging regexes start with ^[^<]* because that ensures that they
# only operate before the first "<". That "<" will be the beginning of the
# author name, ensuring that we don't destroy anything in the commit message
# that looks like time.
#
# The log format uses } characters between each field, and `column` is later
# used to split on them. A } in the commit subject or any other field will
# break this.

HASH="%C(auto,yellow)%h%C(auto,reset)"
RELATIVE_TIME="%C(auto,green)(%ar)%C(auto,reset)"
AUTHOR="%C(auto,bold blue)<%an>%C(auto,reset)"
REFS="%C(auto,red)%d%C(auto,reset)"
SUBJECT="%s"

FORMAT="$HASH $RELATIVE_TIME $AUTHOR $REFS $SUBJECT"

show_git_head() {
    git show -p --pretty="tformat:${FORMAT}"
}

pretty_git_log() {
    git log --graph --pretty="tformat:${FORMAT}" $*
}
